# fly.toml app configuration file generated for betternews-dry-leaf-7620 on 2024-11-10T20:01:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'betternews-dry-leaf-7620'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[env]]
  PORT= '3000'
  DATABASE_URL = 'postgres://postgres:bkot0p1HZ6zrm6W@betternewspg.flycast:5432'